# Generated by Django 5.1.6 on 2025-02-07 23:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(max_length=20, unique=True)),
                ('agent_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('classes', models.ManyToManyField(blank=True, to='formapp.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='forms',
            field=models.ManyToManyField(blank=True, to='formapp.registrationforms'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_no', models.CharField(default='NOT_SET', max_length=20, unique=True)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('phone_numbers', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('contact_no_emergency', models.CharField(max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formapp.agent')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.class')),
                ('registration_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.registrationforms')),
            ],
        ),
        migrations.CreateModel(
            name='ID_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='student_photos/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.registrationforms')),
            ],
        ),
    ]
