# Generated by Django 5.1.6 on 2025-02-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_alter_id_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='id_photos',
            field=models.ManyToManyField(to='formapp.photo'),
        ),
    ]
