# Generated by Django 5.1.6 on 2025-02-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_photo_student_id_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_id',
        ),
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ManyToManyField(blank=True, to='formapp.class'),
        ),
    ]
