# Generated by Django 5.1.6 on 2025-02-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_remove_student_class_id_student_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
