# Generated by Django 5.1.6 on 2025-02-25 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_alter_student_id_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id_photos',
        ),
        migrations.AlterField(
            model_name='id_photo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_photo_set', to='formapp.student'),
        ),
    ]
